### ISSUE TITLE
Failed to update metadata for lvfs on Kubuntu 21.04

### ISSUE THREAD

**Issue by shmu26** [fwupd/fwupd#3652]
**Describe the bug**
When I run
`fwupdmgr refresh`
It fails with the message
`Updating lvfs
Downloading…             [ -                        Downloading…             [ -                        Downloading…             [***************************************]
Downloading…             [**************************Downloading…             [***************************************]
Failed to update metadata for lvfs: checksum failure: failed to verify data, expected 98261db7124c8026fb88f77768787efc2f8355c3
`

**Steps to Reproduce**
Run the above-mentioned command, or open "Discovery" in Kubuntu or the Gnome-software in Ubuntu.

**Expected behavior**
The metadata should be updated

**fwupd version information**
Please provide the version of the daemon and client.

```shell
client version: 1.5.11
compile-time dependency versions
        gusb:   0.3.5

daemon version: 1.5.11

```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):
It was bundled with the distro

**fwupd device information**
Please provide the output of the fwupd devices recognized in your system.

```shell
fwupdmgr get-devices --show-all-devices
System Product Name
│
├─Intel(R) Core™ i7-9700 CPU @ 3.00GHz:
│     Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│     Current version:    0x000000ea
│     Vendor:             Intel
│     GUIDs:              b9a2dd81-159e-5537-a7db-e7101d164d3f
│                         30249f37-d140-5d3e-9319-186b1bd5cac3
│                         809a0b93-8a12-5338-a571-ad5583acf896
│                         50a811ae-a8fd-5cd0-90f4-33583974b789
│     Device Flags:       • Internal device
│   
├─KINGSTON SA400S37480G:
│     Device ID:          5dbeb140337f610d54913c0f43d15fdaa0eafb51
│     Summary:            ATA Drive
│     Current version:    SBFKK1B3
│     Vendor:             Kingston (ATA:0x2646, OUI:0026b7)
│     GUIDs:              d8e02563-67f0-5da4-b388-e3b18a5f0dd3
│                         1ab2d344-65ac-5bc5-adbd-9aab1dfc2be3
│                         b4b189f9-ed32-5438-a5e4-d3313483647a
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Needs shutdown after installation
│                         • Device is usable for the duration of the update
│   
├─System Firmware:
│ │   Device ID:          9faa1c99a611d57becf0cb8087eafd191bfb673e
│ │   Current version:    4611
│ │   Minimum Version:    4611
│ │   Vendor:             System manufacturer (DMI:American Megatrends Inc.)
│ │   GUIDs:              247b3810-2e33-51bf-9ade-4f119f3d0e53
│ │                       230c8b18-8d9b-53ec-838b-6cfc0383493a
│ │                       505f27c1-acb7-52ab-b71a-08be849c28e1
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Needs a reboot after installation
│ │                       • Cryptographic hash verification is available
│ │                       • Device is usable for the duration of the update
│ │ 
│ └─UEFI dbx:
│       Device ID:        362301da643102b9f38477387e2193e57abaa590
│       Summary:          UEFI Revocation Database
│       Current version:  77
│       Minimum Version:  77
│       Vendor:           UEFI:Linux Foundation
│       Install Duration: 1 second
│       GUIDs:            fda6234b-adcb-5105-8515-9af647d29775
│                         f8ff0d50-c757-5dc3-951a-39d86e16f419
│                         c6682ade-b5ec-57c4-b687-676351208742
│                         f8ba2887-9411-5c36-9cee-88995bb39731
│                         7d5759e5-9aa0-5f0c-abd6-7439bb11b9f6
│                         0c7691e1-b6f2-5d71-bc9c-aabee364c916
│       Device Flags:     • Internal device
│                         • Updatable
│                         • Needs a reboot after installation
│     
├─TOSHIBA HDWD120:
│     Device ID:          e421b2fc248391f6fe3e55ddbb3c9043be068bd0
│     Summary:            ATA Drive
│     Current version:    MX4OACF0
│     Vendor:             Toshiba (ATA:0x1179, OUI:000039)
│     GUIDs:              0ca61bbd-a96f-5876-abfc-58fce3f19ab0
│                         f26aeb1a-c0e2-55e9-a43a-31bc5a30bf61
│                         80770ad0-c298-5c20-894b-d805d681048c
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─TPM:
│ │   Device ID:          c6a80ac3a22083423992a3cb15018989f37834d6
│ │   Summary:            TPM 2.0 Device
│ │   Current version:    302.12.0.0
│ │   Vendor:             Intel (TPM:INTC)
│ │   GUIDs:              ff71992e-52f7-5eea-94ef-883e56e034c6
│ │                       34801700-3a50-5b05-820c-fe14580e4c2d
│ │                       8e1cbc5d-5a11-5149-bfea-b6065d5296ba
│ │                       03f304f4-223e-54f4-b2c1-c3cf3b5817c6
│ │                       52d7b679-db28-5bf7-bd87-41d77aeec600
│ │   Device Flags:       • Internal device
│ │ 
│ └─Event Log:
│       Device ID:        58bd405f31c48e6eca290b425f530a94c91e955c
│       GUID:             a25657fe-b5dc-5be0-8b78-8b9dfec678ff
│       Device Flags:     • Internal device
│     
└─UHD Graphics 630 (Desktop 9 Series):
      Device ID:          5792b48846ce271fab11c4a545f7a3df0d36e00a
      Current version:    02
      Vendor:             Intel Corporation (PCI:0x8086)
      GUIDs:              94211b97-22f2-57b3-97e7-15b5023f61e5
                          5b029aee-f2fc-54b4-8247-d7424420c27a
                          e9ceb7d8-e213-5ec4-8805-6330d894b317
                          8655a49b-b4b2-54ff-a6c6-06009dd64f13
      Device Flags:       • Internal device
                          • Cryptographic hash verification is available
```

**Additional questions**

- Operating system and version:
- Have you tried rebooting?
- Yes
- Is this a regression?
- Not sure.
system info:
`inxi -F -z
System:
  Kernel: 5.11.0-31-generic x86_64 bits: 64 
  Desktop: KDE Plasma 5.21.4 
  Distro: Ubuntu 21.04 (Hirsute Hippo) 
Machine:
  Type: Desktop Mobo: ASUSTeK 
  model: PRIME B365M-A v: Rev X.0x 
  serial: <filter> UEFI: American Megatrends 
  v: 1203 date: 10/10/2019 
CPU:
  Info: 8-Core model: Intel Core i7-9700 
  bits: 64 type: MCP L2 cache: 12 MiB 
  Speed: 800 MHz min/max: 800/4700 MHz 
  Core speeds (MHz): 1: 800 2: 800 3: 800 4: 800 
  5: 800 6: 800 7: 800 8: 1834 
Graphics:
  Device-1: Intel CoffeeLake-S GT2 [UHD Graphics 
  630] 
  driver: i915 v: kernel 
  Device-2: IMC Networks XHC Camera type: USB 
  driver: uvcvideo 
  Display: x11 server: X.Org 1.20.11 driver: 
  loaded: modesetting unloaded: fbdev,vesa 
  resolution: 1: 1920x1080~60Hz 
  2: 1920x1080~60Hz 
  OpenGL: 
  renderer: Mesa Intel UHD Graphics 630 (CFL GT2) 
  v: 4.6 Mesa 21.0.3 
Audio:
  Device-1: Intel 200 Series PCH HD Audio 
  driver: snd_hda_intel 
  Device-2: JMTek LLC. USB PnP Audio Device 
  type: USB 
  driver: hid-generic,snd-usb-audio,usbhid 
  Sound Server: ALSA v: k5.11.0-31-generic 
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI 
  Express Gigabit Ethernet 
  driver: r8169 
  IF: enp3s0 state: up speed: 1000 Mbps 
  duplex: full mac: <filter> 
  Device-2: Realtek 802.11ac NIC type: USB 
  driver: rtl8821cu 
  IF: wlx200db0415dd5 state: down mac: <filter> 
Bluetooth:
  Device-1: Cambridge Silicon Radio Bluetooth 
  Dongle (HCI mode) 
  type: USB driver: btusb 
  Report: ID: hci0 state: up running pscan 
  bt-v: 2.1 address: <filter> 
Drives:
  Local Storage: total: 2.26 TiB 
  used: 900.78 GiB (39.0%) 
  ID-1: /dev/sda vendor: Kingston 
  model: SA400S37480G size: 447.13 GiB 
  ID-2: /dev/sdb vendor: Toshiba model: HDWD120 
  size: 1.82 TiB 
Partition:
  ID-1: / size: 139.05 GiB 
  used: 73.6 GiB (52.9%) fs: ext4 dev: /dev/sda5 
  ID-2: /boot/efi size: 96 MiB 
  used: 37.9 MiB (39.5%) fs: vfat dev: /dev/sda2 
Swap:
  ID-1: swap-1 type: partition size: 17.45 GiB 
  used: 3 MiB (0.0%) dev: /dev/sda7 
Sensors:
  System Temperatures: cpu: 29.8 C mobo: 27.8 C 
  Fan Speeds (RPM): N/A 
Info:
  Processes: 321 Uptime: 51m Memory: 15.49 GiB 
  used: 7.62 GiB (49.2%) Shell: fish 
  inxi: 3.3.01 
`

**Comment by hughsie** [comment]
If you download the metadata files with wget, are you getting some kind of captive portal HTML page?

**Comment by shmu26** [comment]
Tell me how to do it and I will give it a try. Give a command to run in terminal, or something.
Right now I am on Kubuntu 20.04 LTS and having the same issue. 
At first I thought it was because of my corporate root certificate but the IT guys say that don't see any block taking place.

**Comment by hughsie** [comment]
e.g. `wget https://cdn.fwupd.org/downloads/firmware.xml.gz`

**Comment by shmu26** [comment]
wget https://cdn.fwupd.org/downloads/firmware.x
ml.gz
--2021-08-19 16:28:05--  https://cdn.fwupd.org/
downloads/firmware.xml.gz
Resolving cdn.fwupd.org (cdn.fwupd.org)... 151.
101.194.49, 151.101.130.49, 151.101.66.49, ...
Connecting to cdn.fwupd.org (cdn.fwupd.org)|151
.101.194.49|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/xml]
Saving to: ‘firmware.xml.gz’

firmware.xm        5.94M  8.57MB/s    in 0.7s


2021-08-19 16:28:08 (8.57 MB/s) - ‘firmware.xml
.gz’ saved [6229586]

**Comment by SnowballV** [comment]
The same issue was reported by three users at Wilders Security Forums, two on Kubuntu 20.04 [[1]](https://www.wilderssecurity.com/threads/kubuntu-20-04-focal-fossa-purrs-like-a-bear.428457/#post-3027086) [[2]](https://www.wilderssecurity.com/threads/kubuntu-20-04-focal-fossa-purrs-like-a-bear.428457/#post-3027112) and one unknown distro and version [[3]](https://www.wilderssecurity.com/threads/kubuntu-20-04-focal-fossa-purrs-like-a-bear.428457/page-2#post-3028206).

In an earlier fwupd thread with a similar issue, [#2089 ](https://github.com/fwupd/fwupd/issues/2089), hughsie diagnosed the issue to the fact that the server was 'OOMing', out of memory, a server reboot fixed that. I wonder if there is any chance that the same problem may be going on?

**Comment by hughsie** [comment]
> server was 'OOMing

That was some time ago when the LVFS was just one VM in a datacenter. It's now a hugely scalable AWS multi-az thing that should survive almost anything.

**Comment by SnowballV** [comment]
OK, thank you very much.
Do you have any thoughts about what may be causing the issue, currently?

**Comment by SnowballV** [comment]
By the way, I was that second mentioned reporter at Wilders.

**Comment by vlrmt** [comment]
I'm facing this error message as well since a few weeks now, on all my Kubuntu 20.04 machines.
I only face this error the 1st time I run Discover after the boot of my machine. Exiting and re-running Discover doesn't generate this error again. Until a subsequent day where Discover mentions the availability of new package updates (rough observation).

Here is what I have in ~/.cache/fwupd/remotes.d/lvfs:

```
-rw-rw-r-- 1 XXX XXX 6250399 août  25 16:28 metadata.xml.gz
-rw-rw-r-- 1 XXX XXX     488 août   3 00:47 metadata.xml.gz.asc
-rw-rw-r-- 1 XXX XXX    2229 août  25 16:28 metadata.xml.gz.jcat
```

As a test, running `wget https://cdn.fwupd.org/downloads/firmware.xml.gz` works correctly on my end.

Another test (after I've already faced message "Failed to update metadata for lvfs" once today):

```
$ fwupdmgr refresh
WARNING: UEFI firmware can not be updated in legacy BIOS mode
  See https://github.com/fwupd/fwupd/wiki/PluginFlag:legacy-bios for more information.
Updating lvfs
Downloading…             [***************************************]
Downloading…             [***************************************]
Successfully downloaded new metadata: 0 local devices supported
```

**Comment by Mastercroft** [comment]
Just to chime in.
Been having the same message pop up every time I open the update/Discovery for the past six weeks, Kubuntu 20.04.

Tested the wget today, will report tomorrow if it works.

**Comment by http91** [comment]
Just reporting here, I've been seeing the exact same message as @Mastercroft for the last maybe one or two months.

**Comment by thomas-zimmerman** [comment]
This may be a subset of the infrastructure; I work at System76, and a customer reports Ubuntu Software will hang with lvfs errors. Running `fwupdmgr refresh` gets the same error:
```
fwupdmgr refresh
Updating lvfs
Downloading… [***************************************]
Failed to update metadata for lvfs: no signature method in results
```
He is in Vermont, and when I run it at the same time in Denver, I get clean results:
```
fwupdmgr refresh
Firmware metadata last refresh: 10 hours ago. Use --force to refresh again.
fwupdmgr refresh --force
Updating lvfs
Downloading…             [***************************************]
Downloading…             [***************************************]
Successfully downloaded new metadata: 0 local devices supported
```

**Comment by hughsie** [comment]
Looking for that error code I see:

	/* should never happen due to %JCAT_VERIFY_FLAG_REQUIRE_SIGNATURE */
	g_set_error_literal(error,
			    FWUPD_ERROR,
			    FWUPD_ERROR_INVALID_FILE,
			    "no signature method in results");

Could this be something to do with the system being upgraded? e.g. if you stop fwupd, then do `rm /var/lib/fwupd/remotes.d/*` then `fwupdmgr refresh --force` does it magically start working?

**Comment by thomas-zimmerman** [comment]
Didn't seem to fix:
```
sudo rm /var/lib/fwupd/remotes.d/*
[sudo] password for lao:
rm: cannot remove '/var/lib/fwupd/remotes.d/lvfs': Is a directory
lao@Sys:~$ fwupdmgr refresh --force
Updating lvfs
Downloading… [***************************************]
Failed to update metadata for lvfs: no signature method in results
```

**Comment by hughsie** [comment]
gahh, sorry, `sudo rm /var/lib/fwupd/remotes.d/* -rf`

**Comment by hughsie** [comment]
Is this snap? If so, I assume snap stores the data somewhere different perhaps?

**Comment by hughsie** [comment]
Okay scrap the upgrade idea, I've traced the failure a bit. On a failing system, try this:

    wget https://cdn.fwupd.org/downloads/firmware.xml.gz
    wget https://cdn.fwupd.org/downloads/firmware.xml.gz.jcat

then do:

	jcat-tool verify firmware.xml.gz.jcat --public-keys /etc/pki/fwupd-metadata
	firmware-02230-stable.xml.gz:
	    PASSED sha1: OK
	    PASSED sha256: OK
	    PASSED pkcs7: O=Linux Vendor Firmware Project,CN=LVFS CA
	    PASSED gpg: 3FC6B804410ED0840D8F2F9748A6D80E4538BAC2

I _suspect_ on a failing system the snap isn't able to read out the certificate store, or maybe the package (the snap?) isn't being built with GPG or PKCS support? I don't see any other way this can fall through to the `no signature method in results` failure.

Perhaps fwupd was built against a different version of libjcat than is installed on the system? If you downgrade libjcat does that work? 0.1.3 had a behaviour change with signatures, although that was released about 15 months ago...

Needless to say, I don't see this on Fedora.

**Comment by thomas-zimmerman** [comment]
Well, isn't this fun:
```
jcat-tool verify firmware.xml.gz.jcat --public-keys /etc/pki/fwupd-metadata | tee jcat.log
firmware-02230-stable.xml.gz:
    FAILED: Failed to open file “./firmware-02230-stable.xml.gz”: No such file or directory
Validation failed

apt policy libjcat1 jcat
libjcat1:
  Installed: 0.1.3-2
  Candidate: 0.1.3-2
  Version table:
 *** 0.1.3-2 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status
jcat:
  Installed: 0.1.3-2
  Candidate: 0.1.3-2
  Version table:
 *** 0.1.3-2 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/universe amd64 Packages
        100 /var/lib/dpkg/status
```
Both firmware.xml.gz and firmware.xml.gz.jcat downloaded and are located in the PWD.

**Comment by thomas-zimmerman** [comment]
That was on my system, which is Pop!OS 21.04; I'm seeing the same error on customer machine that is running Ubuntu 20.04 (with updates all run).

**Comment by hughsie** [comment]
So my guess here was that fwupd was compiled against (i.e. build time, not run time) a newer version of libjcat than is being shipped. I'm pretty sure updating to libjcat 0.1.4 (released 2020-10-23) will fix this, although, you should really update to 0.1.8 for other fixes too.

**Comment by thomas-zimmerman** [comment]
Yep. I tracked this down to the `fwupd` that is built and shipped for System76 customers; when we backed out to the version shipped in 20.04 by Ubuntu, the update works fine. I'm somewhat baffled that I don't see the same error on live hardware or in a VM when trying to recreate this. This is the set of commands that has him fixed (for those that find this error):
```
sudo apt-add-repository -r ppa:system76-dev/stable
sudo apt update
sudo apt full-upgrade
sudo apt remove fwupd
sudo apt install fwupd
```

**Comment by Mastercroft** [comment]
`wget https://cdn.fwupd.org/downloads/firmware.xml.gz` did the trick for me.
Did a `fwupdmgr refresh --force` and it was successful.

No idea how to recreate this.

**Comment by martinvanl** [comment]
fwupdmgr refresh --force fixed it for me as well (kubutu 20.04)
Iǘe had th message for the last two months or so.

**Comment by jackpot51** [comment]
I think we need to get Ubuntu to update fwupd and its dependencies. System76 only ships an override (to our customers on Ubuntu and to Pop users) because the Ubuntu version is missing Launch support and we want maximum hardware support on Pop.

**Comment by SnowballV** [comment]
Regarding `fwupdmgr --force refresh`, on my Kubuntu 20.04 systems, that command didn't fix the "Failed to update metadata for lvfs: checksum failure: failed to verify data" error, the error was back 24 hours later. However, I don't see that error in weekends, if I'm not mistaken. If I recall correctly, there was some update some time ago that limits updates to weekdays, so it also limits the error to weekdays, probably.

**Comment by Mastercroft** [comment]
@SnowballV You are correct, the error is back (this sunday though), three days later.

**Comment by hughsie** [comment]
I'm pretty sure updating libjcat will fix this. I'm not responsible for this in Ubuntu, and I don't think this is a fwupd bug.

**Comment by SnowballV** [comment]
@hughsie,
Do you know how we can find out if updating libjcat is what's needed to fix the issue?
And who at Ubuntu should be contacted regarding this matter?

**Comment by superm1** [comment]
I'm really perplexed why this just started to show up in Ubuntu 21.04, is it just people adopting it more lately?

Neither libjcat nor fwupd in 21.04 have been touched in a very long time.

Regarding reporting it, the correct location would be Launchpad under the appropriate package.

**Comment by SnowballV** [comment]
@superm1,
Good thoughts.

On Kubuntu 20.04, I checked fwupd, and I see it was upgraded to 1.5.11-0ubuntu1~20.04.2 on August 2, 2021.
The fwupd changes list for that version says: * force to use libjcat >= 0.1.3, or signature verification will failed.

I checked libjcat, and I see libjcat1 0.1.3-2~ubuntu20.04.1 was installed August 2, 2021.
It looks like libjcat was not installed before that.

On Kubuntu 20.04, could the recent fwupd upgrade and the installation of libjcat be the cause of the issue? Even if libjcat version is >= 0.1.3 as required by fwupd?

**Comment by superm1** [comment]
This bug report was about 21.04 specifically..  but if this is happening in 20.04 too then yes I agree with hughsie as there was just an SRU there and problems may be possible there.

**Comment by SnowballV** [comment]
@superm1,
Yes, shmu26 opened this issue referring to 21.04 specifically, but soon shmu26 mentioned 20.04 as well, and several other commenters mentioned 20.04 also. Myself, I can't say anything about 21.04, only about 20.04, I'm sorry.
And does SRU stand for Software Requirements Update? Thanks very much.

**Comment by Montg0mery** [comment]
I see this on Pop!_OS 20.04 (non-VM). No captive portal or any other networking issues here.
```
$ fwupdmgr refresh --force 
Updating lvfs
Downloading…             [***************************************]
Failed to update metadata for lvfs: no signature method in results
```

```
$ fwupdmgr --version
client version:	1.5.11
compile-time dependency versions
	gusb:	0.3.4

daemon version:	1.5.11
```

```
$ apt policy fwupd libjcat1 
fwupd:
  Installed: 1.5.11-0ubuntu2pop1~1627329462~20.04~3e64f3f
  Candidate: 1.5.11-0ubuntu2pop1~1627329462~20.04~3e64f3f
  Version table:
 *** 1.5.11-0ubuntu2pop1~1627329462~20.04~3e64f3f 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
     1.5.11-0ubuntu1~20.04.2 500
        500 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
     1.3.9-4ubuntu0.1 500
        500 http://us.archive.ubuntu.com/ubuntu focal-security/main amd64 Packages
     1.3.9-4 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
libjcat1:
  Installed: 0.1.3-2~ubuntu20.04.1
  Candidate: 0.1.3-2~ubuntu20.04.1
  Version table:
 *** 0.1.3-2~ubuntu20.04.1 500
        500 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     0.1.0-2 500
        500 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
```

**Comment by superm1** [comment]
Can someone please open a bug downstream in Ubuntu on it and link the number here?

**Comment by martinvanl** [comment]
I spoke too soon. My error also returned within 2 days.

**Comment by SnowballV** [comment]
@superm1,
I would be happy to create a bug report, were it not that I'll be away for some days, and above all, I'm only a user, no expert at all.
I hope that someone who understands the ins and outs of the issue can create a bug report.

**Comment by SnowballV** [comment]
I'm back from being away for some days.
If by now, no one created a bug report downstream in Ubuntu, as superm1 suggested, I am willing to.
However, as I mentioned, I'm simply a user, no expert like some of you, so it would be most welcome if someone can tell me where to post and what to report, exactly. Thanks very much.

**Comment by JohnnyK007** [comment]
Dear SnowballV and superm1. I have the same issue (i.e., in Kubuntu 20.04, ..." Failed to update metadata for lvfs: no signature method in results"...etc.). According to the previous discussion, the libjcat package can be problematic, but I don't know how to document it. This bug appears on many Ubuntu distros but strangely that it doesn't bother anyone. If you have some idea try to write bug report to https://launchpad.net/ubuntu/+source/libjcat/+bugs

**Comment by Forage** [comment]
Filed: https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1943833

**Comment by Forage** [comment]
After having filed the bug I now see the same behaviour as others have reported here. Initially I had the same error on one system and now it magically works with libjcat 0.1.3 on the same system and a different one just because it's weekend apparently.

**Comment by Laraso** [comment]
Recently installed Kubuntu 20.04. Also getting this error.

**Comment by superm1** [comment]
It's better to rally behind the downstream bug.

**Comment by stevenjaycohen** [comment]
Same issue in Debian 11. Same fix (fwupdmgr --force refresh) works. So Ubuntu may have inherited the issue from Debian.

**Comment by JohnnyK007** [comment]
The "fwupdmgr --force refresh" command will only solve the problem for circa 24 hours and then the problem reappears. Unfortunately, this issue remains unresolved (Ubuntu / Kubuntu) and is unlikely to be addressed in the future.

**Comment by hughsie** [comment]
> and is unlikely to be addressed in the future

At the risk of getting super frustrated: You need to update libjcat and fwupd to non-obsolete versions.

**Comment by superm1** [comment]
So there is a bug tracker in Ubuntu for the libjcat issue, but it was assigned the wrong tasks.
https://bugs.launchpad.net/ubuntu/+source/libjcat/+bug/1943833

I've updated it to add a libjcat task.

**Comment by superm1** [comment]
> Ahh then I'm wrong, I though the LIBJCAT_CHECK_VERSION was 0.1.4.

There was an [effort ](https://github.com/fwupd/fwupd/pull/4182) to fix this by setting the version requirement to 0.1.4, only to discover the macro really is 0.1.3.

**Comment by superm1** [comment]
> I saw the same bug on Arch with KDE Plasma desktop and Discover.

Can you readily reproduce it?  If so can you please run your daemon in verbose mode and share the daemon log?

**Comment by Mastercroft** [comment]
> > I saw the same bug on Arch with KDE Plasma desktop and Discover.
> 
> Can you readily reproduce it? If so can you please run your daemon in verbose mode and share the daemon log?

If it helps and you can tell me how, I can do it on three computers running Kubuntu 20.04.

**Comment by superm1** [comment]
In one terminal run `sudo /usr/libexec/fwupd/fwupd --verbose`.

Reproduce error, share log from first.

**Comment by shmu26** [comment]
If I get back into my Arch installation I will be happy to give it a shot.

**Comment by Mastercroft** [comment]
[fwupd_log.txt](https://github.com/fwupd/fwupd/files/7898509/fwupd_log.txt)

**Comment by superm1** [comment]
I don't see the call to update metadata at the end. Did you run the failure command in another terminal?

**Comment by Mastercroft** [comment]
humm.. it was showing up this morning (8 hours ago) but now I don't get the failure message (tried two out of three setups).

**Comment by superm1** [comment]
Some files that were "good" and "bad" were posted in the downstream bug: https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1943833/+attachment/5555735/+files/lvfs.tar

OK so KDE discover in 5.18 version downloads natively in QT using a QNetworkRequest. AFAICT QNetworkRequest doesn't by default request a compressed file, but needs to explicitly request this to the server: https://stackoverflow.com/questions/2340548/does-qnetworkmanager-get-accept-compressed-replies-by-default

Because of that this bug occurs with KDE discover. KDE discover 5.20.90 and newer have adopted libfwupd for doing the download and should no longer encounter this.

So now next questions:
1.  is this happening for anyone _outside_ of KDE discover still?  Natively with fwupdmgr or anything else?
2. @hughsie can LVFS be configured to not send uncompressed files ever?

**Comment by hughsie** [comment]
> @hughsie can LVFS be configured to not send uncompressed files ever

I'm hesitant to touch the server compression settings, as I know for libsoup-based downloaders we had to do some funky stuff to avoid double-compression.

**Comment by stevenjaycohen** [comment]
> * is this happening for anyone _outside_ of KDE discover still?  Natively with fwupdmgr or anything else?

Debian 11, Gnome 3.38.5
![Screenshot from 2022-01-20 07-05-05](https://user-images.githubusercontent.com/23110485/150335761-ee30066d-e9e2-4cf5-ab20-a00f76b4af22.png)

**Comment by superm1** [comment]
> > @hughsie can LVFS be configured to not send uncompressed files ever
> 
> I'm hesitant to touch the server compression settings, as I know for libsoup-based downloaders we had to do some funky stuff to avoid double-compression.

But if you do something based on user agents?

**Comment by hughsie** [comment]
> But if you do something based on user agents?

I guess we could; do we know the setting that's causing the issue? IIUC, the LVFS is served via gunicorn to the load balancer from Amazon.

**Comment by ScarletNyaa** [comment]
>     1. is this happening for anyone _outside_ of KDE discover still?  Natively with fwupdmgr or anything else?

Debian 11, Gnome 3.38.5, gnome-software 3.38.1-1. Temporarily fixed with fwupdmgr refresh --force, comes back after reboot.

**Comment by LarnuUK** [comment]
I too have been seeing this message for some time. I've just been ignoring it, but it does get annoying. Probably does date back to around August last year when I first saw it. Happens only the first time I open Discover and it checks for updates, not on subsequent attempts.

**Comment by cpsyctc** [comment]
I am getting it repeatedly in Ubuntu 20.04 4 LTS in "Ubuntu Software"

**Comment by martin-ac** [comment]
I'm getting the message on three PC / NB - different hardware - all running Kubuntu 20.04.4 LTS
where the newest version of Discovery is 5.18.7 
but until now to me it looks like I only get it after a restart of the system AND only once a day.
I'm quite sure I've never seen the error message a second time after e.g. closing Discovery without installing updates and again starting the update process - no matter if I restart the system in between or not. Maybe I have to wait for a next day or 24 h?

I will doublecheck this the next days and report. Until now nothing I've done helped permanently.

**Comment by JohnnyK007** [comment]
This mistake has been here for a year. I confirm that even after yesterday's automated update of the "libjcat1" and "fwupd" packages (in Kubuntu 20.04 LTS + Discover) this error persists (i.e., installed version libjcat1: 0.1.4-0ubuntu0.20.04.1). Today I got the same mistake in Discover again. I'll see what it's like 24 hours later.

**Comment by SnowballV** [comment]
> I confirm that even after yesterday's automated update of the "libjcat1" and "fwupd" packages (in Kubuntu 20.04 LTS + Discover) this error persists (i.e., installed version libjcat1: 0.1.4-0ubuntu0.20.04.1).

I expected or at least hoped that last weeks update of the libjcat1 package (plus fwupd packages) in Kubuntu 20.04 (Focal) might have fixed the issue in Discover package manager - but it did not. I still get the mentioned error at least once a day.
So much for updating libjcat to 0.1.4 as a solution, I suppose

By the way, I'm not sure about what is concluded in the Launchpad bug report [fwupd failed to update metadata for lvfs](https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1943833), regarding a fix for the issue in Discover in Kubuntu 20.04 (Focal).

**Comment by JoshuaKahn** [comment]
I am getting this issue on Kubuntu 20.04, KDE version 5.18.8, Discover 5.18.7.

**Comment by JoshuaKahn** [comment]
Ok, I'm not sure if it was a specific update but I'm no longer seeing this error. 

It's possible that it may return though.

**Comment by martin-ac** [comment]
@JoshuaKahn : I had this "feeling" several times in the last year because I didn't get the error message every time I used Discover to install updates. But until now it returned on every machine I'm using. Would be very nice if you leave a comment as soon as the error message returns at yours - thanks in advance.
Today I again had the case that I saw the error message when starting Discover after I received the info of updates have to be installed. This time I did NOT install updates but did a shutdown to power off and a restart afterwards and with running system started Discover but this time did NOT get the lvfs error message, only found the updates to install. So now I'm quite sure this lvfs error message only gets triggered ONCE.
AND: to me it looks like I can do what ever I like to do, the lvfs error message seems to come back only after at least one restart AND the situation that new updates for the system have been found to get installed - I do not let them be installed automatically but only get the message about available updates - AND I start Discover. This is where an when I see the lvfs error message.
Can someone confirm this? Is one of the experts able to give some advice for additional tests?

**Comment by hughsie** [comment]
> Is one of the experts able to give some advice for additional tests

I don't think there is any QA being done with Kubuntu or KDE more generally, sorry. I think either KDE needs to use the same library as everyone else (libfwupd) or someone reimplementing the download code needs to look at this. There's not a lot we can do.

**Comment by cpsyctc** [comment]
I am not an expert at all and I am using Ubuntu 20.04 not Kubuntu. I saw the error once but it went away and the seemingly related problems I was having went away when I tracked them down to an entry in /etc/apt/sources.list.d/ that was pointing to a deceased repository.  I do think out of that experience that the error messages in the ubuntu updating system are quite seriously flawed as I think a much more informative message than the one I was seeing could have been created (apt-get update gave me the necessary clue though I had to remember /etc/apt/sources.list.d/ before things fell into place.

**Comment by JoshuaKahn** [comment]
> @JoshuaKahn : I had this "feeling" several times in the last year because I didn't get the error message every time I used Discover to install updates. But until now it returned on every machine I'm using. Would be very nice if you leave a comment as soon as the error message returns at yours - thanks in advance. Today I again had the case that I saw the error message when starting Discover after I received the info of updates have to be installed. This time I did NOT install updates but did a shutdown to power off and a restart afterwards and with running system started Discover but this time did NOT get the lvfs error message, only found the updates to install. So now I'm quite sure this lvfs error message only gets triggered ONCE. AND: to me it looks like I can do what ever I like to do, the lvfs error message seems to come back only after at least one restart AND the situation that new updates for the system have been found to get installed - I do not let them be installed automatically but only get the message about available updates - AND I start Discover. This is where an when I see the lvfs error message. Can someone confirm this? Is one of the experts able to give some advice for additional tests?

Indeed, the error returned today. It occurred after several restarts since the last time I saw it, and it only occurred when I opened the Update page in Discover after seeing the 'updates are available' icon on my notification bar, clicking on it, and waiting for the loading bar to complete.

**Comment by SnowballV** [comment]
Does anyone use Kubuntu 22.04?
Is the 'Failed to update metadata for lvfs' issue in Discover fixed in Kubuntu 22.04, or is it still the same as in Kubuntu 20.04 and 21.04?
I'm still on Kubuntu 20.04, I don't update until the 22.04.1 dot release, later, so I cannot test whether the issue is or is not fixed in Kubuntu 22.04.

**Comment by LightTemplar** [comment]
> Does anyone use Kubuntu 22.04? If so, can you confirm the 'Failed to update metadata for lvfs' issue no longer affects Discover on Kubuntu 22.04? 

I have fresh installed Kubuntu 22.04 for a couple of days and there is still no such error message. Next to it, I have two machines with Kubuntu 20.04 and there I observe this pretty regularly.

**Comment by SnowballV** [comment]
@LightTemplar,
Thank you very much for confirming.

**Comment by Mastercroft** [comment]
> https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1943833, comment 36, says the issue no longer affects plasma-discover on Jammy (22.04). Does anyone use Kubuntu 22.04? If so, can you confirm the 'Failed to update metadata for lvfs' issue no longer affects Discover on Kubuntu 22.04? I'm still on Kubuntu 20.04, I don't update until the 22.04.1 dot release, so I cannot test whether the issue is truly fixed in Kubuntu 22.04. (NB My apologies for the many edits in this post.)

> > Does anyone use Kubuntu 22.04? If so, can you confirm the 'Failed to update metadata for lvfs' issue no longer affects Discover on Kubuntu 22.04?
> 
> I have fresh installed Kubuntu 22.04 for a couple of days and there is still no such error message. Next to it, I have two machines with Kubuntu 20.04 and there I observe this pretty regularly.

I can testify on this as well, running three setups, two with 20.04 and one with 22.04.
Both 20's show the message regularly while the 22 has not for the past month.

**Comment by NiklasSchmitt-cnic** [comment]
I got this message on Kubuntu 18.04 with fwupdmgr version 1.2.14 and don't know what I can do. Waiting for an manually cdn update?
`
$ fwupdmgr --force -v refresh
(fwupdmgr:24927): FuCommon-DEBUG: 12:42:49.131: creating path /home/bla/.cache/fwupd
(fwupdmgr:24927): Fwupd-DEBUG: 12:42:49.134: looking for os-release at /etc/os-release
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.135: downloading https://cdn.fwupd.org/downloads/firmware.xml.gz to /home/ad.ks.de/nschmitt/.cache/fwupd/lvfs-metadata.xml.gz
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.283: progress: 0%
Downloading…             [-                                      ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.284: progress: 0%
Downloading…             [ -                                     ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.284: progress: 0%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.284: progress: 0%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.284: progress: 0%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.284: progress: 0%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.284: progress: 1%
Downloading…             [                                       ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.285: progress: 1%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.285: progress: 1%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.285: progress: 1%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.285: progress: 1%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.286: progress: 1%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.287: progress: 1%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.287: progress: 1%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.287: progress: 2%
Downloading…             [                                       ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.288: progress: 2%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.288: progress: 2%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.288: progress: 2%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.288: progress: 2%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.288: progress: 2%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.288: progress: 2%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.289: progress: 3%
Downloading…             [*                                      ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.290: progress: 3%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.290: progress: 3%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.290: progress: 3%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.291: progress: 3%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.291: progress: 3%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.291: progress: 3%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.291: progress: 4%
Downloading…             [*                                      ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.301: progress: 4%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.301: progress: 4%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.301: progress: 4%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.302: progress: 4%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.302: progress: 4%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.302: progress: 5%
Downloading…             [*                                      ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.302: progress: 5%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.305: progress: 6%
Downloading…             [**                                     ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.305: progress: 6%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.309: progress: 7%
Downloading…             [**                                     ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.310: progress: 8%
Downloading…             [***                                    ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.317: progress: 9%
Downloading…             [***                                    ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.318: progress: 10%
Downloading…             [***                                    ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.321: progress: 11%
Downloading…             [****                                   ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.321: progress: 12%
Downloading…             [****                                   ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.324: progress: 12%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.324: progress: 13%
Downloading…             [*****                                  ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.330: progress: 14%
Downloading…             [*****                                  ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.330: progress: 15%
Downloading…             [*****                                  ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.331: progress: 16%
Downloading…             [******                                 ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.331: progress: 17%
Downloading…             [******                                 ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.334: progress: 18%
Downloading…             [*******                                ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.335: progress: 19%
Downloading…             [*******                                ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.338: progress: 19%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.338: progress: 20%
Downloading…             [*******                                ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.341: progress: 21%
Downloading…             [********                               ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.342: progress: 22%
Downloading…             [********                               ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.342: progress: 23%
Downloading…             [********                               ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.343: progress: 24%
Downloading…             [*********                              ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.343: progress: 25%
Downloading…             [*********                              ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.344: progress: 25%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.344: progress: 26%
Downloading…             [**********                             ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.344: progress: 27%
Downloading…             [**********                             ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.345: progress: 28%
Downloading…             [**********                             ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.345: progress: 29%
Downloading…             [***********                            ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.348: progress: 30%
Downloading…             [***********                            ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.348: progress: 31%
Downloading…             [************                           ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.352: progress: 32%
Downloading…             [************                           ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.352: progress: 32%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.356: progress: 33%
Downloading…             [************                           ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.357: progress: 34%
Downloading…             [*************                          ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.358: progress: 35%
Downloading…             [*************                          ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.358: progress: 36%
Downloading…             [**************                         ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.361: progress: 37%
Downloading…             [**************                         ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.362: progress: 38%
Downloading…             [**************                         ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.362: progress: 38%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.362: progress: 39%
Downloading…             [***************                        ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.364: progress: 40%
Downloading…             [***************                        ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.364: progress: 41%
Downloading…             [***************                        ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.367: progress: 42%
Downloading…             [****************                       ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.368: progress: 43%
Downloading…             [****************                       ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.368: progress: 44%
Downloading…             [*****************                      ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.369: progress: 45%
Downloading…             [*****************                      ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.371: progress: 45%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.371: progress: 46%
Downloading…             [*****************                      ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.373: progress: 47%
Downloading…             [******************                     ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.373: progress: 48%
Downloading…             [******************                     ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.376: progress: 49%
Downloading…             [*******************                    ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.376: progress: 50%
Downloading…             [*******************                    ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.377: progress: 51%
Downloading…             [*******************                    ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.377: progress: 51%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.380: progress: 52%
Downloading…             [********************                   ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.380: progress: 53%
Downloading…             [********************                   ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.382: progress: 54%
Downloading…             [*********************                  ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.382: progress: 55%
Downloading…             [*********************                  ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.384: progress: 56%
Downloading…             [*********************                  ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.385: progress: 57%
Downloading…             [**********************                 ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.387: progress: 58%
Downloading…             [**********************                 ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.387: progress: 58%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.388: progress: 59%
Downloading…             [***********************                ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.388: progress: 60%
Downloading…             [***********************                ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.391: progress: 61%
Downloading…             [***********************                ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.391: progress: 62%
Downloading…             [************************               ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.394: progress: 63%
Downloading…             [************************               ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.394: progress: 64%
Downloading…             [************************               ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.395: progress: 64%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.396: progress: 65%
Downloading…             [*************************              ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.406: progress: 66%
Downloading…             [*************************              ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.406: progress: 67%
Downloading…             [**************************             ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.406: progress: 68%
Downloading…             [**************************             ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.406: progress: 69%
Downloading…             [**************************             ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.407: progress: 70%
Downloading…             [***************************            ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.407: progress: 70%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.407: progress: 71%
Downloading…             [***************************            ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.407: progress: 72%
Downloading…             [****************************           ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.409: progress: 73%
Downloading…             [****************************           ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.409: progress: 74%
Downloading…             [****************************           ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.410: progress: 75%
Downloading…             [*****************************          ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.410: progress: 76%
Downloading…             [*****************************          ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.413: progress: 77%
Downloading…             [******************************         ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.413: progress: 77%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.413: progress: 78%
Downloading…             [******************************         ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.413: progress: 79%
Downloading…             [******************************         ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.416: progress: 80%
Downloading…             [*******************************        ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.417: progress: 81%
Downloading…             [*******************************        ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.418: progress: 82%
Downloading…             [*******************************        ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.419: progress: 83%
Downloading…             [********************************       ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.423: progress: 83%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.423: progress: 84%
Downloading…             [********************************       ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.424: progress: 85%
Downloading…             [*********************************      ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.424: progress: 86%
Downloading…             [*********************************      ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.425: progress: 87%
Downloading…             [*********************************      ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.425: progress: 88%
Downloading…             [**********************************     ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.427: progress: 89%
Downloading…             [**********************************     ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.427: progress: 90%
Downloading…             [***********************************    ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.428: progress: 90%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.428: progress: 91%
Downloading…             [***********************************    ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.431: progress: 92%
Downloading…             [***********************************    ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.431: progress: 93%
Downloading…             [************************************   ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.433: progress: 94%
Downloading…             [************************************   ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.434: progress: 95%
Downloading…             [*************************************  ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.437: progress: 96%
Downloading…             [*************************************  ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.437: progress: 96%
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.438: progress: 97%
Downloading…             [*************************************  ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.438: progress: 98%
Downloading…             [************************************** ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.439: progress: 99%
Downloading…             [************************************** ](fwupdmgr:24927): FuMain-DEBUG: 12:42:49.439: progress: 100%
Downloading…             [***************************************]
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.480: downloading https://cdn.fwupd.org/downloads/firmware.xml.gz.asc to /home/bla/.cache/fwupd/lvfs-metadata.xml.gz.asc
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc
(fwupdmgr:24927): FuMain-DEBUG: 12:42:49.496: progress: 100%

Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature
`

**Comment by hughsie** [comment]
The 1.2.x versions haven't really seen any maintenance since ~2020. For reference 1.7.x is the current _stable_ release. You should ask Ubuntu to rev the version to something supported; you're probably missing out on other firmware updates that depend on a new enough fwupd version.

**Comment by Samisafool** [comment]
I have this on Arch

fwupd version: 
runtime   org.freedesktop.fwupd         1.8.6

**Comment by hughsie** [comment]
@Samisafool ; You have `Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature`?

**Comment by Bananaman** [comment]
Same issue on Fedora Workstation 36, which uses fwupdmgr 1.8.6.

`sudo fwupdmgr refresh --force`

Result: Failed to update metadata for lvfs: checksum failure: failed to verify data, expected 20771e... (etc, can't write it all on phone, doesn't matter).

Using wget to grab the Metadata as described in this ticket showed me a gzip file, not HTML captive portals or anything like that.

This issue appeared yesterday or thereabouts.

**Comment by Bananaman** [comment]
Just tried it on a second machine. Totally different hardware. Same distro.

It shows the same error but different hash: 3e476a...

**Comment by gaarf** [comment]
Fedora here, also started seeing `failed to verify data, expected 3e476a...` today

**Comment by wgcvc** [comment]
Hello,

Facing the issue `failed to verify data, expected...` on a Lenovo Carbon X1 7th Gen with the following:

```
$ uname -a
Linux william-ThinkPad-X1-Carbon-7th 5.4.0-126-generic #142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20.1
Release:	20.1
Codename:	ulyssa

$ fwupdmgr --version
runtime   org.freedesktop.fwupd         1.7.5
runtime   com.dell.libsmbios            2.4
compile   org.freedesktop.gusb          0.3.4
runtime   org.kernel                    5.4.0-126-generic
compile   org.freedesktop.fwupd         1.7.5
runtime   org.freedesktop.gusb          0.3.4
```

I also tried to:
```
wget https://cdn.fwupd.org/downloads/firmware.xml.gz
wget https://cdn.fwupd.org/downloads/firmware.xml.gz.jcat
jcat-tool verify firmware.xml.gz.jcat --public-keys /etc/pki/fwupd-metadata
```

but I got:
```
firmware-04761-stable.xml.gz:
    FAILED: Failed to open file “./firmware-04761-stable.xml.gz”: No such file or directory
Validation failed
```
