### ISSUE TITLE
`fwupdmgr refresh` fails due to invalid signature

### ISSUE THREAD

**Issue by cocreature** [fwupd/fwupd#391]
Running `fwupdmgr refresh` fails on my system with the following error message:
```shell
$ fwupdmgr refresh
Fetching metadata https://s3.amazonaws.com/lvfsbucket/downloads/firmware.xml.gz
Downloading…           [***************************************]
Fetching signature https://s3.amazonaws.com/lvfsbucket/downloads/firmware.xml.gz.asc

Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature
```

This is a new issue, on wednesday (07.02.2018), refreshing worked just fine. I can reproduce this on another machine as well (also Archlinux).

```shell
$ fwupdmgr --version
client version: 1.0.4
daemon version: 1.0.4
compile-time dependency versions
        appstream-glib: 0.7.4
        gusb:   0.2.11
```

- Operating system and version:
Archlinux 64bit
- How did you install fwupd (ex: `from source`, `pacman`, `apt-get`, etc):
`pacman`
- Have you tried rebooting?
Yes
- Are you using an NVMe disk?
Yes
- Is secure boot enabled (only for the UEFI plugin)?
No

**Comment by superm1** [comment]
Yep, I can also reproduce on Ubuntu with master.

**Comment by hughsie** [comment]
I'll try regenerating the metadata first as a quick fix.

**Comment by hughsie** [comment]
Right, that worked, I'll have a look at the old files and try to work out what went wrong. I have a suspicion it's my fault and the staging LVFS accidentally uploaded metadata with the test key.

**Comment by hughsie** [comment]
Nope, it appears the right key was used:

    $ gpg2 --verify firmware.xml.gz.asc firmware.xml.gz
    gpg: Signature made Wed 07 Feb 2018 12:47:04 GMT
    gpg:                using RSA key 48A6D80E4538BAC2
    gpg: BAD signature from "Linux Vendor Firmware Service <sign@fwupd.org>" [unknown]

(I have the public key imported system wide on this machine)

**Comment by cocreature** [comment]
Thanks for the fix, that was impressively fast! I’ll leave it up to you to decide when to close the issue.

**Comment by hughsie** [comment]
In the event log:

    2018-02-07 12:47:03 | ???.???.???.??? | dellqa | Uploaded file 05e0d0906098a57c4d0aa71d5f5fc4e620e7ee03-Signed_1152921504627420111.cab to stable /lvfs/upload

...which is what triggered the metadata rebuild (correctly).

**Comment by hughsie** [comment]
And nothing untoward in the uwsgi logs:

    [pid: 28217|app: 0|req: 1175/1175] ???.???.???.??? () {52 vars in 1302 bytes} [Wed Feb  7 12:47:00 2018] POST /lvfs/upload => generated 317 bytes in 10536 msecs (HTTP/1.1 302) 
4 headers in 526 bytes (2 switches on core 0)
uploading /var/www/lvfs/downloads/firmware-testing.xml.gz as downloads/firmware-testing.xml.gz
uploading /var/www/lvfs/downloads/firmware-testing.xml.gz.asc as downloads/firmware-testing.xml.gz.asc
uploading /var/www/lvfs/downloads/firmware.xml.gz as downloads/firmware.xml.gz
uploading /var/www/lvfs/downloads/firmware.xml.gz.asc as downloads/firmware.xml.gz.asc

**Comment by hughsie** [comment]
$ sha1sum firmware.xml.gz*
6443eac9f838c6b12edaaf2fcd56cf140b1e5309  firmware.xml.gz
3268b224447fa12b5dcd95dc8f9c1be59ecf5fe9  firmware.xml.gz.1
e817446b3a96aadd1ad9c5a4de72d20a1f2db1d7  firmware.xml.gz.asc

..where the .1 is after the rebuild.

**Comment by hughsie** [comment]
Ohh, that's expected, other firmwares got pushed to stable in the meantime (new `<releases>` are appearing... but that should have synced the cdn too -- but there is nothing in the logs.

**Comment by hughsie** [comment]
I can't work this one out -- I'll close and we can reopen if this every happens again.

**Comment by rpbikker** [comment]
Please reopen, it's happening again. Since yesterday I get "Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature" on two machines running Fedora 27.

**Comment by rpbikker** [comment]
It's gone again. If nobody changed anything, it seems to be something intermittent...

**Comment by brumle80** [comment]
reopening due to:

```
fwupdmgr get-updates -v                                                                                                                                                                                                                                                                              16:19:47  ✘ 1 
Firmware metadata has not been updated for 30 days and may not be up to date.

Update now? (Requires internet connection) [y|N]: y
(fwupdmgr:15127): Fu-DEBUG: creating path /root/.cache/fwupdmgr
(fwupdmgr:15127): Fwupd-DEBUG: looking for os-release at /etc/os-release
(fwupdmgr:15127): Fu-DEBUG: downloading https://cdn.fwupd.org/downloads/firmware.xml.gz to /root/.cache/fwupdmgr/lvfs-metadata.xml.gz
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
(fwupdmgr:15127): Fu-DEBUG: progress: 26%
Downloading…           [**********                             ](fwupdmgr:15127): Fu-DEBUG: progress: 54%
Downloading…           [*********************                  ](fwupdmgr:15127): Fu-DEBUG: progress: 81%
Downloading…           [*******************************        ](fwupdmgr:15127): Fu-DEBUG: progress: 100%
Downloading…           [***************************************]
(fwupdmgr:15127): Fu-DEBUG: downloading https://cdn.fwupd.org/downloads/firmware.xml.gz.asc to /root/.cache/fwupdmgr/lvfs-metadata.xml.gz.asc
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc
(fwupdmgr:15127): Fu-DEBUG: progress: 100%

Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature

```

**Comment by hughsie** [comment]
@brumle80 can you upload /root/.cache/fwupdmgr/firmware.xml.gz and /root/.cache/fwupdmgr/firmware.xml.gz to this ticket please.

**Comment by hughsie** [comment]
I managed to find someone else having the same problem. This is what I see:

    $ shasum /home/hughsie/.cache/fwupdmgr/lvfs-metadata.xml.gz*
    f14067a80825e321ab36c9c0063e1766d4f78e30  /home/hughsie/.cache/fwupdmgr/lvfs-metadata.xml.gz
    e1a2f0b2402c6e9dc9b3b217366471a362460c4b  /home/hughsie/.cache/fwupdmgr/lvfs-metadata.xml.gz.asc

    $ gpg /home/hughsie/.cache/fwupdmgr/lvfs-metadata.xml.gz.asc
    gpg: assuming signed data in `/home/hughsie/.cache/fwupdmgr/lvfs-metadata.xml.gz'
    gpg: Signature made Tue 06 Mar 2018 09:06:39 GMT using RSA key ID 4538BAC2
    gpg: Good signature from "Linux Vendor Firmware Service <sign@fwupd.org>"

Now, the other person provided me with files that were downloaded from the CDN just a few minutes ago:

    shasum /home/hughsie/Downloads/metadata.xml.gz*
    f14067a80825e321ab36c9c0063e1766d4f78e30  /home/hughsie/Downloads/metadata.xml.gz
    e0d1a5cbb1fa4dd0a7f9e79505b1b9bb57d50d28  /home/hughsie/Downloads/metadata.xml.gz.asc

Hmm, so the detached signature is different.

    $ gpg /home/hughsie/Downloads/metadata.xml.gz.asc
    gpg: assuming signed data in `/home/hughsie/Downloads/metadata.xml.gz'
    gpg: Signature made Wed 28 Feb 2018 20:07:37 GMT using RSA key ID 4538BAC2
    gpg: BAD signature from "Linux Vendor Firmware Service <sign@fwupd.org>"

A file generated on the 28th Feb?!

**Comment by hughsie** [comment]
Some followup; it seems the CDN is shipping old files for some zones. I've purged all zones manually, and it should "fix" it, although we need some kind of root cause analysis and a plan to detect this again automatically in the future.

**Comment by brumle80** [comment]
the purge fixed it as it's working fine now, thanks for the quick resolve.

**Comment by HawkinsTheWizard** [comment]
Still/again Getting the same
```
(fwupdmgr:2051): Fu-DEBUG: 16:46:58.763: creating path /root/.cache/fwupdmgr
(fwupdmgr:2051): Fwupd-DEBUG: 16:46:58.765: looking for os-release at /etc/os-release
(fwupdmgr:2051): Fu-DEBUG: 16:46:58.765: downloading https://cdn.fwupd.org/downloads/firmware.xml.gz to /root/.cache/fwupdmgr/lvfs-metadata.xml.gz
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
(fwupdmgr:2051): Fu-DEBUG: 16:46:59.386: progress: 24%
Downloading…           [*********                              ](fwupdmgr:2051): Fu-DEBUG: 16:46:59.386: progress: 50%
Downloading…           [*******************                    ](fwupdmgr:2051): Fu-DEBUG: 16:46:59.444: progress: 76%
Downloading…           [*****************************          ](fwupdmgr:2051): Fu-DEBUG: 16:46:59.444: progress: 100%
Downloading…           [***************************************]
(fwupdmgr:2051): Fu-DEBUG: 16:46:59.449: downloading https://cdn.fwupd.org/downloads/firmware.xml.gz.asc to /root/.cache/fwupdmgr/lvfs-metadata.xml.gz.asc
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc
(fwupdmgr:2051): Fu-DEBUG: 16:46:59.513: progress: 100%

Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature

```

**Comment by gildo** [comment]
Same here

**Comment by hughsie** [comment]
I've purged manually; which seems to fix things for me too, but we really need a way to purge triggered from the LVFS.

**Comment by snowyu** [comment]
Again now:

```bash
> fwupdmgr refresh
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
Downloading…           [***************************************]
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc

Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature

> shasum ~/.cache/fwupdmgr/lvfs-metadata.xml.gz*
d4a73a0924d9bed830ddff85f748dbe6bb3a3473  fwupdmgr/lvfs-metadata.xml.gz
be5d50b6fd62ed59edd0e10396a4f7499b56dfa8  fwupdmgr/lvfs-metadata.xml.gz.asc
```
It should refresh CDN automatically

**Comment by hughsie** [comment]
Different error this time; a permissions error on the server. I think I've fixed up everything now, but I'll do a root cause after breakfast.

**Comment by hughsie** [comment]
See https://github.com/hughsie/lvfs-website/issues/138 for the root cause.

**Comment by ilya40umov** [comment]
I've run into the same problem today:
```
fwupdmgr refresh 
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
Downloading…           [***************************************]
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc

Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature
```

**Comment by hughsie** [comment]
Works now, right? I broke the metadata sync when converting everything to Python 3.

**Comment by ilya40umov** [comment]
@hughsie ran it a few more times and still the same thing, I'm guessing it's the cdn cache

**Comment by ilya40umov** [comment]
@hughsie I've run it now and it has worked. Thanks a quick fix!

**Comment by tjyrinki** [comment]
At the moment still broken around here, but probably just a matter of waiting for all of cdn to catch.

**Comment by laptop006** [comment]
Broken right now (Accessing a Fastly node in Sydney)

**Comment by laptop006** [comment]
... although a retry after a few minutes did work.

**Comment by madsl** [comment]
Tested right now:

# fwupdmgr refresh
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
Downloading…             [***************************************] Less than one minute remaining…
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc

Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature

**Comment by jat255** [comment]
Also having this issue:

```sh
OS: Arch Linux 
Kernel: x86_64 Linux 5.0.7-arch1-1-ARCH
Shell: zsh 5.7.1
Resolution: 3840x1200
DE: KDE 5.56.0 / Plasma 5.15.4
WM: KWin
CPU: Intel Core i7-8650U @ 8x 4.2GHz
```

```
$ sudo fwupdmgr refresh
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
Downloading…             [***************************************] Less than one minute remaining…
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc

Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature
```

**Comment by frankvw2017** [comment]
Today, 23 May 2019, Ubuntu 18.04:

```
$ sudo fwupdmgr refresh
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
Downloading…           [***************************************]
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc

Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature
```

**Comment by laferuben** [comment]
The same thing, once again. @hughsie

**Comment by lrvega** [comment]
I'm seeing the same thing again after enabling `/etc/fwupd/remotes.d/lvfs-testing.conf` :
```
$ sudo fwupdmgr refresh && fwupdmgr update
Fetching metadata https://cdn.fwupd.org/downloads/firmware-testing.xml.gz
Downloading…           [***************************************]
Fetching signature https://cdn.fwupd.org/downloads/firmware-testing.xml.gz.asc

Failed to update metadata for lvfs-testing: '48A6D80E4538BAC2' is not a valid signature
```

**Comment by laptop006** [comment]
I see two obvious ways to fix this permanently.

1. Embed the signature in the metadata file.
2. Have the signature actually be a meta manifest, at a known name, listing the manifest files which themselves are named by a version, and possibly keep the last two or three so races can be handled.

This, of course, wouldn't be backwards compatible, but at least you could fix it for the future (plus it's a nice chance to make any other backwards incompatible changes that you might want).

**Comment by hughsie** [comment]
So, the reason we don't bundle these together is so we can download the *tiny* detached signature, and then if it has changed from what we have already we download the few-hundred-k metadata file. I suppose one thing to check would be the number of days where the metadata *hasn't* changed as it seems to change much more frequently than when LVFS was a little project only used by one or two OEMs. If it indeed changes every day we could just embed the signature into the .xml.gz somehow, or just do a non-detached-signature at the risk of making the metadata harder to check without gpg2.

The best way of doing this is probably like you suggest, so we get the json manifest and use the manifest checksum to do the "has the remote changed" check. Then if changed, grab the metadata and signature which have a unique per-generation filename. Of course, that's 3 requests although with keep-alive maybe that's not such a big deal.

**Comment by superm1** [comment]
>Then if changed, grab the metadata and signature which have a unique per-generation filename

And for backwards compatibility you'll need to have latest symlink pointing to the per-generation filename.

**Comment by fethomm** [comment]
Same here just now:
 `fwupdmgr get-updates -v  
Firmware-Metadaten wurden seit 30 Tagen nicht aktualisiert und sind möglicherweise nicht auf dem neuesten Stand.

Jetzt aktualisieren? (Erfordert Internetverbindung) [y|N]: y
(fwupdmgr:13132): FuCommon-DEBUG: 07:19:16.491: creating path /root/.cache/fwupdmgr
(fwupdmgr:13132): Fwupd-DEBUG: 07:19:16.491: looking for os-release at /etc/os-release
(fwupdmgr:13132): FuMain-DEBUG: 07:19:16.492: downloading https://cdn.fwupd.org/downloads/firmware-testing.xml.gz to /root/.cache/fwupdmgr/lvfs-testing-metadata.xml.gz
Metadaten werden abgerufen https://cdn.fwupd.org/downloads/firmware-testing.xml.gz
(fwupdmgr:13132): GLib-GIO-DEBUG: 07:19:16.499: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(fwupdmgr:13132): dconf-DEBUG: 07:19:16.499: watch_fast: "/system/proxy/" (establishing: 0, active: 0)
(fwupdmgr:13132): dconf-DEBUG: 07:19:16.499: watch_fast: "/system/proxy/http/" (establishing: 0, active: 0)
(fwupdmgr:13132): GLib-DEBUG: 07:19:16.499: posix_spawn avoided (fd close requested) 
(fwupdmgr:13132): dconf-DEBUG: 07:19:16.499: watch_fast: "/system/proxy/https/" (establishing: 0, active: 0)
(fwupdmgr:13132): dconf-DEBUG: 07:19:16.501: watch_fast: "/system/proxy/ftp/" (establishing: 0, active: 0)
(fwupdmgr:13132): dconf-DEBUG: 07:19:16.501: watch_fast: "/system/proxy/socks/" (establishing: 0, active: 0)
(fwupdmgr:13132): dconf-DEBUG: 07:19:16.501: unwatch_fast: "/system/proxy/" (active: 0, establishing: 1)
(fwupdmgr:13132): dconf-DEBUG: 07:19:16.501: unwatch_fast: "/system/proxy/http/" (active: 0, establishing: 1)
(fwupdmgr:13132): dconf-DEBUG: 07:19:16.501: unwatch_fast: "/system/proxy/https/" (active: 0, establishing: 1)
(fwupdmgr:13132): dconf-DEBUG: 07:19:16.502: unwatch_fast: "/system/proxy/ftp/" (active: 0, establishing: 1)
(fwupdmgr:13132): dconf-DEBUG: 07:19:16.502: unwatch_fast: "/system/proxy/socks/" (active: 0, establishing: 1)
(fwupdmgr:13132): GLib-GIO-DEBUG: 07:19:16.503: _g_io_module_get_default: Found default implementation libproxy (GLibproxyResolver) for ‘gio-proxy-resolver’
(fwupdmgr:13132): dconf-DEBUG: 07:19:16.516: watch_established: "/system/proxy/" (establishing: 0)
(fwupdmgr:13132): dconf-DEBUG: 07:19:16.516: watch_established: "/system/proxy/http/" (establishing: 0)
(fwupdmgr:13132): dconf-DEBUG: 07:19:16.517: watch_established: "/system/proxy/https/" (establishing: 0)
(fwupdmgr:13132): dconf-DEBUG: 07:19:16.517: watch_established: "/system/proxy/ftp/" (establishing: 0)
(fwupdmgr:13132): dconf-DEBUG: 07:19:16.517: watch_established: "/system/proxy/socks/" (establishing: 0)
(fwupdmgr:13132): GLib-GIO-DEBUG: 07:19:16.520: _g_io_module_get_default: Found default implementation gnutls (GTlsBackendGnutls) for ‘gio-tls-backend’
(fwupdmgr:13132): FuMain-DEBUG: 07:19:16.694: progress: 8%
Herunterladen …          [***                                    ](fwupdmgr:13132): FuMain-DEBUG: 07:19:16.694: progress: 22%
Herunterladen …          [********                               ] Weniger als eine Minute verbleiben…(fwupdmgr:13132): FuMain-DEBUG: 07:19:16.695: progress: 37%
Herunterladen …          [**************                         ] Weniger als eine Minute verbleiben…(fwupdmgr:13132): FuMain-DEBUG: 07:19:16.696: progress: 51%
Herunterladen …          [*******************                    ](fwupdmgr:13132): FuMain-DEBUG: 07:19:16.697: progress: 65%
Herunterladen …          [*************************              ](fwupdmgr:13132): FuMain-DEBUG: 07:19:16.717: progress: 78%
Herunterladen …          [******************************         ](fwupdmgr:13132): FuMain-DEBUG: 07:19:16.718: progress: 93%
Herunterladen …          [************************************   ](fwupdmgr:13132): FuMain-DEBUG: 07:19:16.718: progress: 100%
Herunterladen …          [***************************************]
(fwupdmgr:13132): FuMain-DEBUG: 07:19:16.729: downloading https://cdn.fwupd.org/downloads/firmware-testing.xml.gz.asc to /root/.cache/fwupdmgr/lvfs-testing-metadata.xml.gz.asc
Signatur wird abgerufen https://cdn.fwupd.org/downloads/firmware-testing.xml.gz.asc
(fwupdmgr:13132): FuMain-DEBUG: 07:19:16.758: progress: 100%

Failed to update metadata for lvfs-testing: '48A6D80E4538BAC2' is not a valid signature`

**Comment by schildbach** [comment]
I too get

```
$ sudo fwupdmgr refresh
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
Downloading…           [***************************************]
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc

Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature
```

**Comment by fethomm** [comment]
Found the cause for the error in my case. The package _fwupd-amd64-signed_ had been removed on Debian Sid the other day. After reinstalling it, everything worked fine.

**Comment by lrvega** [comment]
> Found the cause for the error in my case. The package _fwupd-amd64-signed_ had been removed on Debian Sid the other day. After reinstalling it, everything worked fine.

That worked for me. Thanks!

**Comment by superm1** [comment]
@fethomm @Irvega
I don't see any connection between those two actions.  That package is only used when a UEFI capsule is installed, not a metadata refresh.

**Comment by lrvega** [comment]
@superm1 then perhaps it was coincidental and the correct metadata/signatures have been pushed?

**Comment by superm1** [comment]
I agree it's coincidental; it's likely a timing problem.  See the above comment for details and ideas on how to approach it.
https://github.com/hughsie/fwupd/issues/391#issuecomment-513218878

**Comment by bestouff** [comment]
Had it just today:
```
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
Downloading…             [***************************************] Less than one minute remaining…
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc

Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature
```

**Comment by arcivanov** [comment]
Same here for me on Fedora 30.

**Comment by g2p** [comment]
Got this after upgrading to Ubuntu 19.10 eoan.
For anyone who needs a simple fix: `sudo rm -rf /root/.cache/fwupd`

**Comment by superm1** [comment]
`/root/.cache`?  The cache is created by fwupdmgr I thought, so it should be `~/.cache` unless you've been running `fwupdmgr` as root (which generally you shouldn't be doing)

**Comment by superm1** [comment]
I'm going to add the regression label to this since this keeps popping up from time to time.  The _proper_ fix is to do something like https://github.com/fwupd/fwupd/issues/391#issuecomment-513218878 which will take some time to do the plumbing on both sides.

**Comment by gaeljw** [comment]
`rm -rf ~/.cache/fwupd` worked for me (indeed, not run as root)

**Comment by LinuxOnTheDesktop** [comment]
```
$ sudo fwupdmgr refresh
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
Downloading…           [***************************************]
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc

Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature
$ rm -rf ~/.cache/fwupd
$ sudo fwupdmgr refresh
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
Downloading…           [***************************************]
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc

Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature
```

**Comment by Dridi** [comment]
Same for me today, except that I removed this instead:

```
sudo rm -rv /root/.cache/fwupdmgr
```

After attempting a new refresh it failed again, but this time the cache appeared in `/root/.cache/fwupd`, but removing that directory also doesn't make a difference...

**Comment by kflak** [comment]
Happened to me as well on arch linux this morning. /root/.cache/fwudmgr doesn't exist on my system, and removing ~/.cache/fwupd/* doesn't help either.

**Comment by bigfreak85** [comment]
and next one same problem here@archlinux

**Comment by adm-bome** [comment]
And ubuntu[19.10]

**Comment by azpekt** [comment]
And another one on pop_os 19.10

**Comment by akunszt** [comment]
The same problem here. This might be the root cause, at least on my machine:
```
trantor ~ # LANG=C gpg -v ~/.cache/fwupd/lvfs-metadata.xml.gz.asc
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
gpg: armor header: Version: GnuPG v2.0.22 (GNU/Linux)
gpg: assuming signed data in '/root/.cache/fwupd/lvfs-metadata.xml.gz'
gpg: Signature made Mon Feb 17 13:26:24 2020 CET
gpg:                using RSA key 48A6D80E4538BAC2
gpg: using pgp trust model
gpg: BAD signature from "Linux Vendor Firmware Service <sign@fwupd.org>" [unknown]
gpg: binary signature, digest algorithm SHA1, key algorithm rsa2048
```

**Comment by hughsie** [comment]
The PKCS signer exploded overnight. I'll do a root cause analysis later this evening, but I've manually restarted it, which caused the signing queue to become unstuck, which caused the cdn sync to hapen successfully. It should all work correctly now.

**Comment by segadora** [comment]
Im having the problem now
```
(fwupdmgr:28732): FuMain-DEBUG: 08:51:40.446: downloading https://cdn.fwupd.org/downloads/firmware.xml.gz.asc to /home/cn/.cache/fwupdmgr/lvfs-metadata.xml.gz.asc
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc
(fwupdmgr:28732): FuMain-DEBUG: 08:51:40.450: progress: 100%

Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature
```

**Comment by segadora** [comment]
works now

**Comment by hughsie** [comment]
> Im having the problem now

Try now; the CDN PURGE wasn't working correctly.

**Comment by nolen777** [comment]
I'm hitting the same thing this morning on Ubuntu 18.04

**Comment by sirocyl** [comment]
Just experienced this same issue from Clear Linux.
```
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc
Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature```

This seems to recur on a somewhat regular, almost calendary basis, on February.
Could it possibly be an issue handling the February case of 28 days in the month and/or leap day calculation?

**Comment by sirocyl** [comment]
> Just experienced this same issue from Clear Linux.

Retried a minute after posting, and it seems to have updated successfully, (Thank you, if someone did something server-side to fix it. :D )

**Comment by hughsie** [comment]
We're working on a fix: https://github.com/fwupd/fwupd/pull/1827

**Comment by mptyspace** [comment]
Also having this at the moment =/

**Comment by beltrame** [comment]
Same here

**Comment by BjoernDaase** [comment]
Seeing this again in Fedora 32. This is the concrete output:  
```
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
Downloading…             [***************************************]
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc

Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature
```

Do you want me to open a new issue or do we keep the discussion in this issue?

**Comment by hughsie** [comment]
If you want to test all this out, you currently need to install both libjcat and fwupd from git master, although new tarballs won't be much further away.

**Comment by kerneltime** [comment]
I am running into this on ubuntu 20.04

**Comment by superm1** [comment]
The fix is in the fwupd 1.4.x branch, which is not present in Ubuntu 20.04

**Comment by LinuxOnTheDesktop** [comment]
Is the 1.4 branch in the Flatpak version? It seems not to be.

**Comment by hughsie** [comment]
> Is the 1.4 branch in the Flatpak version

I'm just building 1.4.4 in flathub now.

**Comment by j14s** [comment]
Ubuntu 20.04. Same issue.

**Comment by pixelyo** [comment]
> Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature

Ubuntu Server 20.04. Same issue.

**Comment by jDally987** [comment]
Jumping on the bandwagon
```
jojojo@JWHISKEYE:~$ sudo fwupdmgr refresh -v              
(fwupdmgr:4344): FuCommon-DEBUG: 23:38:41.144: creating path /home/jojojo/.cache/fwupd
(fwupdmgr:4344): Fwupd-DEBUG: 23:38:41.147: looking for os-release at /etc/os-release
(fwupdmgr:4344): FuMain-DEBUG: 23:38:41.147: downloading https://cdn.fwupd.org/downloads/firmware.xml.gz to /home/jojojo/.cache/fwupd/lvfs-metadata.xml.gz
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
(fwupdmgr:4344): FuMain-DEBUG: 23:38:41.333: progress: 0%
Downloading…             [-                                      ](fwupdmgr:4344): FuMain-DEBUG: 23:38:41.333: progress: 0%
Downloading…             [ -                                     ](fwupdmgr:4344): FuMain-DEBUG: 23:38:41.333: progress: 0%
(fwupdmgr:4344): FuMain-DEBUG: 23:38:41.335: progress: 1%
Downloading…             [                                       ](fwupdmgr:4344): FuMain-DEBUG: 23:38:41.336: progress: 1%
[...]
(fwupdmgr:4344): FuMain-DEBUG: 23:38:41.413: downloading https://cdn.fwupd.org/downloads/firmware.xml.gz.asc to /home/jojojo/.cache/fwupd/lvfs-metadata.xml.gz.asc
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc
(fwupdmgr:4344): FuMain-DEBUG: 23:38:41.429: progress: 100%

Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature
```
When trying get-updates:
```
jojojo@JWHISKEYE:~$ fwupdmgr get-updates -v
No releases found for device: no HWIDs matched b31aa89d-cfb8-5c67-8502-ce76a9e7b580
```
Additionally: not sure if this is the right place for this; and I'm kind of a noob with linux in general still so maybe I'm just dumb, but I may have some kind of malware on my machine at the moment, which I have no idea if it has anything to do with this, but I suspect it poisons the DNS cache somehow (have had problems with all kinds of websites in a browser, some sketchy certificate issues)... for what it's worth. Highly doubt fwupd is a likely *cause* of that though, if anything merely a symptom - I'm not completely sure if I have anything malicious at all at this point (been trying to diagnose for months) but if I do, it's very deep in the UEFI or something, and started in Windows soo. But in case anyone else sees this who has been wondering the same thing on their machines.

**Comment by Nidian** [comment]
Getting the same error

Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
Downloading…           [***************************************]
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc

Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature


What was the fix for this?

Thank you

**Comment by SergejGorev** [comment]
Same error on Elitebook 845 G7.

`

Fetching metadata https://cdn.fwupd.org/downloads/firmware-testing.xml.gz
Downloading…             [***************************************]
Fetching signature https://cdn.fwupd.org/downloads/firmware-testing.xml.gz.asc

Failed to update metadata for lvfs-testing: '48A6D80E4538BAC2' is not a valid signature
`

**Comment by alchemyconsulting** [comment]
Same error on recent ubuntu 20.04.1 server install:
```
/usr/bin/fwupdmgr refresh --no-metadata-check
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
Downloading…             [***************************************]
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc

Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature
```

**Comment by axtimwalde** [comment]
It is happening again currently:
```
sudo fwupdmgr refresh
[sudo] password for mapa: 
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
Downloading…             [***************************************]
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc

Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature
```

**Comment by axtimwalde** [comment]
As of now works again, that was fast!  Thanks!

**Comment by mfenniak** [comment]
I am currently getting the same error reported here, as of the time of this comment:
```
$ sudo fwupdmgr refresh
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
Downloading…             [***************************************]
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc

Failed to update metadata for lvfs: '48A6D80E4538BAC2' is not a valid signature
```

**Comment by alchemyconsulting** [comment]
I got this regularly across servers for weeks.  `apt purge fwupd` solved it - I don't know about the wisdom of including this by default in Ubuntu but if your servers don't support/need automatic firmware updates then just disable it permanently.

**Comment by superm1** [comment]
The fix to this was introduced in 1.4.x with switching to jcat based metadata.

Unfortunately that means that 1.3.x and earlier will continue to encounter it from time to time due to cdn mirroring delays.

If you continue to encounter it on 1.3.x and earlier please try again in a few minutes.
