### ISSUE TITLE
CET Platform is supported, but CET OS support is not

### ISSUE THREAD

**Issue by 64-bitman** [fwupd/fwupd#8217]
**Describe the question**
As the title says. However, CET OS support used to be supported but for some reason recently it was changed to unsupported? I tried checking DNF's history, but there wasn't any system upgrades or possibly related actions on that date. Any way to possibly resupport it again? Using Framework 13 laptop with ryzen 7640u cpu.

Distro: Fedora 41 Workstation
```shell
Host Security ID: HSI:3! (v1.9.27)

HSI-1
✔ BIOS firmware updates:         Enabled
✔ Fused platform:                Locked
✔ Supported CPU:                 Valid
✔ TPM empty PCRs:                Valid
✔ TPM v2.0:                      Found
✔ UEFI bootservice variables:    Locked
✔ UEFI platform key:             Valid
✔ UEFI secure boot:              Enabled

HSI-2
✔ SPI write protection:          Enabled
✔ IOMMU:                         Enabled
✔ Platform debugging:            Locked
✔ TPM PCR0 reconstruction:       Valid

HSI-3
✔ SPI replay protection:         Enabled
✔ CET Platform:                  Supported
✔ Pre-boot DMA protection:       Enabled
✔ Suspend-to-idle:               Enabled
✔ Suspend-to-ram:                Disabled

HSI-4
✔ SMAP:                          Enabled
✘ Processor rollback protection: Disabled
✘ Encrypted RAM:                 Not supported

Runtime Suffix -!
✔ fwupd plugins:                 Untainted
✔ Linux kernel lockdown:         Enabled
✔ Linux swap:                    Encrypted
✔ Linux kernel:                  Untainted
✘ CET OS Support:                Not supported

This system has HSI runtime issues.
 » https://fwupd.github.io/hsi.html#hsi-runtime-suffix

Host Security Events
  2024-11-22 23:39:42:  ✘ CET OS Support changed: Supported → Not supported
  2024-11-22 23:33:45:  ✔ Kernel is no longer tainted
  2024-11-16 04:43:18:  ✘ Kernel is tainted
  2024-11-15 19:48:19:  ✔ Kernel lockdown enabled
  2024-11-15 19:48:19:  ✔ Secure Boot enabled
```
 

**fwupd version information**
Please provide the version of the daemon and client if applicable to your current installation of `fwupd`.

```shell
compile   org.freedesktop.fwupd         1.9.27
compile   com.hughsie.libxmlb           0.3.21
compile   org.freedesktop.Passim        0.1.8
compile   com.hughsie.libjcat           0.2.2
runtime   org.freedesktop.fwupd-efi     1.6
compile   org.freedesktop.gusb          0.4.9
runtime   com.hughsie.libxmlb           0.3.21
runtime   com.hughsie.libjcat           0.2.2
runtime   org.freedesktop.Passim        0.1.8
runtime   org.freedesktop.gusb          0.4.9
runtime   org.kernel                    6.11.10-300.fc41.x86_64
runtime   org.freedesktop.fwupd         1.9.27
```

**Comment by 64-bitman** [comment]
> What does this print?
> 
> ```
> /usr/libexec/fwupd/fwupd-detect-cet
> echo $?
> ```

It prints 1

**Comment by hughsie** [comment]
> It prints 1

So that means that the CET protection is not enabled. @superm1 I get the same on Fedora 41; do you remember how we debugged this last time? For my the helper is compiled with:

	ccache cc -Iplugins/cpu/libfwupdcethelper.a.p -Iplugins/cpu -I../../plugins/cpu -I. -I../.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O0 -g -Wfatal-errors -Waggregate-return -Wunused -Warray-bounds -Wcast-align -Wclobbered -Wdeclaration-after-statement -Wdiscarded-qualifiers -Wduplicated-branches -Wduplicated-cond -Wempty-body -Wfloat-equal -Wformat=2 -Wformat-nonliteral -Wformat-security -Wformat-signedness -Wignored-qualifiers -Wimplicit-function-declaration -Wimplicit-int -Wincompatible-pointer-types -Winit-self -Wint-conversion -Wlogical-op -Wmaybe-uninitialized -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-parameter-type -Wmissing-prototypes -Wnested-externs -Wno-cast-function-type -Wno-address-of-packed-member -Wno-unknown-pragmas -Wno-missing-field-initializers -Wno-strict-aliasing -Wno-suggest-attribute=format -Wno-unused-parameter -Wno-nonnull-compare -Wno-analyzer-use-of-uninitialized-value -Wno-analyzer-fd-double-close -Wold-style-definition -Woverride-init -Wpointer-arith -Wredundant-decls -Wreturn-type -Wshadow -Wsign-compare -Wstrict-aliasing -Wstrict-prototypes -Wswitch-default -Wtype-limits -Wundef -Wuninitialized -Wunused-but-set-variable -Wunused-variable -Wvla -Wwrite-strings -fstack-protector-strong -DFWUPD_COMPILATION -D_DEFAULT_SOURCE -D_BSD_SOURCE -D__BSD_VISIBLE -D_XOPEN_SOURCE=700 -D_GNU_SOURCE -D_DARWIN_C_SOURCE=900000 -fPIC -fcf-protection=none -MD -MQ plugins/cpu/libfwupdcethelper.a.p/fu-cpu-helper-cet-common.S.o -MF plugins/cpu/libfwupdcethelper.a.p/fu-cpu-helper-cet-common.S.o.d -o plugins/cpu/libfwupdcethelper.a.p/fu-cpu-helper-cet-common.S.o -c ../../plugins/cpu/fu-cpu-helper-cet-common.S
	ccache cc -Iplugins/cpu/fwupd-detect-cet.p -Iplugins/cpu -I../../plugins/cpu -I. -I../.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O0 -g -Wfatal-errors -Waggregate-return -Wunused -Warray-bounds -Wcast-align -Wclobbered -Wdeclaration-after-statement -Wdiscarded-qualifiers -Wduplicated-branches -Wduplicated-cond -Wempty-body -Wfloat-equal -Wformat=2 -Wformat-nonliteral -Wformat-security -Wformat-signedness -Wignored-qualifiers -Wimplicit-function-declaration -Wimplicit-int -Wincompatible-pointer-types -Winit-self -Wint-conversion -Wlogical-op -Wmaybe-uninitialized -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-parameter-type -Wmissing-prototypes -Wnested-externs -Wno-cast-function-type -Wno-address-of-packed-member -Wno-unknown-pragmas -Wno-missing-field-initializers -Wno-strict-aliasing -Wno-suggest-attribute=format -Wno-unused-parameter -Wno-nonnull-compare -Wno-analyzer-use-of-uninitialized-value -Wno-analyzer-fd-double-close -Wold-style-definition -Woverride-init -Wpointer-arith -Wredundant-decls -Wreturn-type -Wshadow -Wsign-compare -Wstrict-aliasing -Wstrict-prototypes -Wswitch-default -Wtype-limits -Wundef -Wuninitialized -Wunused-but-set-variable -Wunused-variable -Wvla -Wwrite-strings -fstack-protector-strong -DFWUPD_COMPILATION -D_DEFAULT_SOURCE -D_BSD_SOURCE -D__BSD_VISIBLE -D_XOPEN_SOURCE=700 -D_GNU_SOURCE -D_DARWIN_C_SOURCE=900000 -fcf-protection=full -MD -MQ plugins/cpu/fwupd-detect-cet.p/fu-cpu-helper-cet.c.o -MF plugins/cpu/fwupd-detect-cet.p/fu-cpu-helper-cet.c.o.d -o plugins/cpu/fwupd-detect-cet.p/fu-cpu-helper-cet.c.o -c ../../plugins/cpu/fu-cpu-helper-cet.c
	rm -f plugins/cpu/libfwupdcethelper.a && gcc-ar csrDT plugins/cpu/libfwupdcethelper.a plugins/cpu/libfwupdcethelper.a.p/fu-cpu-helper-cet-common.S.o
	cc  -o plugins/cpu/fwupd-detect-cet plugins/cpu/fwupd-detect-cet.p/fu-cpu-helper-cet.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-z,defs -Wl,-z,now -Wl,-z,ibt,-z,shstk plugins/cpu/libfwupdcethelper.a

**Comment by superm1** [comment]
Is the glibc env variable set?

**Comment by hughsie** [comment]
I forgot all about cc3e67b8bbb522344cfe0a3e3ff0ac940d9e537c -- you're correct:

    $ GLIBC_TUNABLES=glibc.cpu.hwcaps=SHSTK ./plugins/cpu/fwupd-detect-cet && echo $?
    0

And using fwupdmgr (on my work AMD machine):

    Runtime Suffix -!
    ✔ CET OS Support:                Supported

@64-bitman what do you get when using `GLIBC_TUNABLES`?

**Comment by 64-bitman** [comment]
> I forgot all about [cc3e67b](https://github.com/fwupd/fwupd/commit/cc3e67b8bbb522344cfe0a3e3ff0ac940d9e537c) -- you're correct:
> 
> ```
> $ GLIBC_TUNABLES=glibc.cpu.hwcaps=SHSTK ./plugins/cpu/fwupd-detect-cet && echo $?
> 0
> ```
> 
> And using fwupdmgr (on my work AMD machine):
> 
> ```
> Runtime Suffix -!
> ✔ CET OS Support:                Supported
> ```
> 
> @64-bitman what do you get when using `GLIBC_TUNABLES`?

running `GLIBC_TUNABLES=glibc.cpu.hwcaps=SHSTK /usr/libexec/fwupd/fwupd-detect-cet` I still get an error code of 1, or should I being using a git build of fwupd?

**Comment by superm1** [comment]
> running GLIBC_TUNABLES=glibc.cpu.hwcaps=SHSTK /usr/libexec/fwupd/fwupd-detect-cet I still get an error code of 1, or should I being using a git build of fwupd

You don't need to be running a git build.  We've had this in for a while.  I'm suspect that there has been a regression in glibc.  Can you look at your package update logs and see if those correlate?

**Comment by superm1** [comment]
CC @hjl-tools, any regressions you're aware in glibc in this area?

**Comment by 64-bitman** [comment]
> > running GLIBC_TUNABLES=glibc.cpu.hwcaps=SHSTK /usr/libexec/fwupd/fwupd-detect-cet I still get an error code of 1, or should I being using a git build of fwupd
> 
> You don't need to be running a git build. We've had this in for a while. I'm suspect that there has been a regression in glibc. Can you look at your package update logs and see if those correlate?

Looked over my package logs again and there were no system upgrades on that list or anything I could see that would be related.

```shell
166 dnf install mpv                                                                                    2024-11-22 23:57:08                 7
165 dnf install totem-video-thumbnailer                                                                2024-11-22 23:41:51                 1
164 dnf install mokutil                                                                                2024-11-22 22:19:57                 1
163 dnf install dkms                                                                                   2024-11-22 22:08:49                 2
162 dnf install kernel-devel                                                                           2024-11-22 22:06:23                 4
161 dnf remove gnome-shell-extension-screenshot-window-sizer                                           2024-11-22 22:03:36                 2
```

**Comment by hughsie** [comment]
Fixed in cc3e67b8bbb522344cfe0a3e3ff0ac940d9e537c I think.

**Comment by ValdikSS** [comment]
> Fixed in [cc3e67b](https://github.com/fwupd/fwupd/commit/cc3e67b8bbb522344cfe0a3e3ff0ac940d9e537c) I think.

That applies only to the systemd service?
I have the same described issue on Fedora 42. 

>✘ CET OS Support:                Not supported
>
>Host Security Events
> 2025-10-06 06:18:18:  ✔ Kernel lockdown enabled
> 2025-09-25 00:26:16:  ✘ CET OS Support changed: Supported → Not supported
> 2025-01-02 19:24:03:  ✔ Secure Boot enabled
> 2024-01-16 07:09:55:  ✔ CET OS Support changed: Not supported → Supported

And `GLIBC_TUNABLES=glibc.cpu.hwcaps=SHSTK /usr/libexec/fwupd/fwupd-detect-cet` exits with 0 (without GLIBC_TUNABLES it exits with 1)

```
$ sudo fwupdtool security 2>&1 | grep 'CET OS Support:'
✘ CET OS Support:                Not supported

$ sudo GLIBC_TUNABLES=glibc.cpu.hwcaps=SHSTK fwupdtool security 2>&1 | grep 'CET OS Support:'
✔ CET OS Support:                Supported
```

**Comment by hughsie** [comment]
I don't think fwupdtool *can* set the GLIBC_TUNABLES after starting...

**Comment by pebkacerr** [comment]
<img width="1892" height="1137" alt="Image" src="https://github.com/user-attachments/assets/a0f4ba6b-863f-4438-9106-702b6f2af964" />

<img width="1282" height="791" alt="Image" src="https://github.com/user-attachments/assets/71a96652-854a-415e-98ef-063d9adc81e2" />

&nbsp;
I still encounter this problem.

---

## Report details
- **Date generated:**                              2026-01-26 19:24:52

## Hardware Information:
- **Hardware Model:**                              Lenovo ThinkPad P1 Gen 8
- **Memory:**                                      64.0 GiB
- **Processor:**                                   Intel® Core™ Ultra 7 265H × 16
- **Graphics:**                                    Intel® Graphics (ARL)
- **Disk Capacity:**                               2.5 TB

## Software Information:
- **Firmware Version:**                            N4EET19W (1.05 )
- **OS Name:**                                     Gentoo Linux
- **OS Type:**                                     64-bit
- **GNOME Version:**                               48
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.18.7-gentoo-thinkpad-p1-gen8


----

fwupdmgr --version
compile   info.libusb                   1.0.29
compile   com.hughsie.libxmlb           0.3.21
compile   com.hughsie.libjcat           0.2.3
compile   org.freedesktop.fwupd         2.0.18
runtime   org.freedesktop.fwupd-efi     1.8
runtime   com.hughsie.libxmlb           0.3.21
runtime   com.hughsie.libjcat           0.2.3
runtime   org.kernel                    6.18.7-gentoo-thinkpad-p1-gen8
runtime   org.freedesktop.fwupd         2.0.18

fwupdtool security 2>&1 | grep 'CET OS Support:'
✘ CET OS Support:                Not supported

GLIBC_TUNABLES=glibc.cpu.hwcaps=SHSTK fwupdtool security 2>&1 | grep 'CET OS Support:'
✔ CET OS Support:                Supported

systemctl show fwupd -p Environment
Environment=GLIBC_TUNABLES=glibc.cpu.hwcaps=SHSTK FWUPD_SYSCALL_FILTER=systemd

zcat /proc/config.gz | grep -E 'CONFIG_X86_KERNEL_IBT|SHADOW_STACK'
CONFIG_X86_KERNEL_IBT=y
CONFIG_X86_USER_SHADOW_STACK=y
CONFIG_ARCH_HAS_USER_SHADOW_STACK=y

-----

My packages:

 sys-kernel/gentoo-kernel
-  Latest version available: 6.18.7
-  Latest version installed: 6.18.7

sys-apps/fwupd
- Latest version available: 2.0.18
- Latest version installed: 2.0.18

sys-apps/fwupd-efi
- Latest version available: 1.8
- Latest version installed: 1.8

**Comment by MNarath1** [comment]
> /usr/libexec/fwupd/fwupd-detect-cet && echo $

this looks like a similar issue to mine after updating to 44 https://github.com/fwupd/fwupd/issues/10277

**Comment by leahanderson1** [comment]
yeah lol i'm running into this on my Gentoo install.

**Comment by schildbach** [comment]
I have this problem with Ubuntu 26.04.

**Comment by hughsie** [comment]
If the OS isn't compiled with CET (and enabled at runtime) there's not much fwupd can do.

**Comment by leahanderson1** [comment]
> I did some more digging on stock Fedora 44 and Ubuntu 26.04 installs and the good news is neither `fwupd` or distros are to blame and the root cause has been through a fix cycle upstream in the kernel but it is incomplete to this day.
> 
> Please join me on a journey into this rabbit hole haha.
> 
> Given that `fwupd-detect-cet` and `libc.so.6` are both correctly built with CET (`readelf -n` shows `IBT, SHSTK` on both). The piece missing it is the kernel's vDSO and dumping it from a running process revealed the following:
> 
> ```
> $ readelf -n /tmp/vdso.so
> Displaying notes found in: .note
>   Owner        Data size  Description
>   Linux        0x00000004 Unknown note type: (0x00000000)
>   Linux        0x00000001 OPEN
>   GNU          0x00000014 NT_GNU_BUILD_ID
>   FDO          0x0000005c FDO_PACKAGING_METADATA
> ```
> 
> No `x86 feature` property while glibc's shadow-stack auto-enable requires that note on every object in the process's link map, including the vDSO and one missing link breaks it for the whole process. That's also why `GLIBC_TUNABLES=glibc.cpu.hwcaps=SHSTK` makes the check pass but it skips that requirement instead of satisfying it.
> 
> Going deeper it became two short parts:
> 
> **Part 1:** Since 2020, the kernel's vDSO linker script deliberately [discarded](https://lists.openwall.net/linux-kernel/2020/03/27/507) `.note.gnu.property` and the reasoning was that it was unused. True in 2020 but no longer true once glibc started [checking](https://sourceware.org/git/gitweb.cgi?p=glibc.git;h=541641a3de8d89464151bd879552755e882c832e) it at the end of 2023. Retaining notes was added back [here](https://git.kernel.org/tip/8717b02b8c030dc0c4b55781b59e88def0a1a92f) and landed in mainline in January 2026.
> 
> **Part 2:** The remaining blocker seems to be finishing fixing a typo that was made in the compile flags. The previous fix alone did not solve it because the vDSO's own object files are not compiled with `-fcf-protection=return` due to this typo. In the current (3aa1dcaa4f6f) kernel sources `arch/x86/entry/vdso/common/Makefile.include` reads:
> 
> ```
> flags-$(X86_USER_SHADOW_STACK) += $(call cc-option, -fcf-protection=return)
> ```
> 
> Which is missing the `CONFIG_` prefix, this typo was caught by kernel developer review in January 2026. A fix was posted but per the merged fix own change log, it was deliberately dropped before merge:
> 
> > "Chris's script also found that `CONFIG_X86_USER_SHADOW_STACK` was missing `CONFIG_`, but it needs a different fix." [source](https://git.kernel.org/torvalds/c/a48acbaf99d239e60a09a9e2b7d0f7e9feb62769)
> 
> This ended my journey into the rabbit hole with some answers that make sense to me. My conclusion is to wait for that different fix mentioned to land upstream in the kernel and this issue should solve itself.
> 
> Unfortunately there hasn't been much progress since January this year. The fix seems pretty straight forward but the maintainer said a different fix was needed so it is probably not as simple as adding the `CONFIG_` prefix back.
> 
> Because this lives in shared upstream code it explains why it reproduced identically on both Fedora 44 and Ubuntu 26.04 for me. Which would also imply it is likely no distro can pass this check cleanly until it's resolved upstream in the kernel.

i remember the check working on arch linux a few months back

**Comment by zearp** [comment]
Can any of the maintainers (@hughsie or @superm1) please chime in and share their thoughts on my last two comments?

https://github.com/fwupd/fwupd/issues/8217#issuecomment-5286166636
https://github.com/fwupd/fwupd/issues/8217#issuecomment-5288184698

Do you share my conclusion that this issue will fix itself once upstream fixes it so the note is added back? Auto enable won't work until thats added back. It is the root cause and until thats is fixed not a single binary will run with shadow stacking enabled unless `GLIBC_TUNABLES=glibc.cpu.hwcaps=SHSTK` is set, which is not a proper solution. I'm sorry if I posted the wrong info in the wrong place. I hoped it would be helpful but if unwanted please let me know.

**Comment by wirl** [comment]
As mentioned in the post above due to shadow stacks auto enable being broken in the kernel until [this](https://git.kernel.org/torvalds/c/a48acbaf99d239e60a09a9e2b7d0f7e9feb62769) is fixed the check currently only shows shadow stack state for the `fwupdmgr` process and not the system itself. As that is the only process running with `GLIBC_TUNABLES=glibc.cpu.hwcaps=SHSTK` forced into its environment. Which is done by cc3e67b8bbb522344cfe0a3e3ff0ac940d9e537c. Without that environment variable the check fails as @ValdikSS showed earlier. This would imply that shadow stacking is disabled system wide else it would pass when run with `fwupdtool` as well.

My question to @superm1 / @hughsie: Is it expected behaviour that the check does not indicate any system wide protection but only checks if shadow stacking can work for a single process when force enabled by an environment setting? Maybe a new issue is warranted for this? I know Fedora is planning to [implement](https://forge.fedoraproject.org/fesco/tickets/issues/3636) shadow stacks in F46. They do not seem aware auto enable is currently broken.

As end user I expected passing this check indicates global/system wide protection is working but as it stands now this is not the case. This should resolve itself once the kernel fixes the missing vdso note but until then maybe the docs or security report can clarify that passing the check does not indicate global shadow stack protection? I also think that once the kernel fixes this that `fwupdmgr` should no longer force that environment variable as it should be auto enabled when the process starts and not need to be force enabled.

**Comment by hughsie** [comment]
I must admit I was surprised the GLIBC_TUNABLES was required. When the kernel is fixed we can certainly remove that.
